### ISSUE TITLE
html 没有压缩吗

### ISSUE THREAD

**Issue by dd1994** [yanhaijing/fis3-base#10]
配置里好像没有写 HTML 压缩规则啊

**Comment by yanhaijing** [comment]
html，压缩没必要吧？！！！！！！！！！

**Comment by yanhaijing** [comment]
不过也有这样的插件应该

**Comment by dd1994** [comment]
很有必要啊，你看百度首页的 HTML 不是也压缩过的。
我试了一下，压缩能够大概省 20% 的体积，这在 html 文件比较大时效果很明显的

**Comment by yanhaijing** [comment]
我们过亿的页面都没压缩，如果你特别在意的话可以压缩，性能不会有啥提升，但是能节省流量

**Comment by yanhaijing** [comment]
https://github.com/pianist829/fis-optimizer-html-compress 可以用这个插件
