### ISSUE TITLE
是否可以将components改为node_modules支持？

### ISSUE THREAD

**Issue by simplees** [yanhaijing/fis3-base#12]
现在采用的 fis-components 对组件进行管理，但是组件库不全，加上更新繁琐且不够及时。是不是可以考虑支持 npm 对组件库进行管理，fis 也有对应的 [node_modules](https://github.com/fex-team/fis3-hook-node_modules) ，可以很平滑过渡到这个方案。

**Comment by yanhaijing** [comment]
npm和node_modules 应该是互斥的，不能同时搞两个，我们在用components ，换成npm应该不麻烦吧！

**Comment by simplees** [comment]
嗯，其实更换起来不麻烦。只是我在之前用 fis3-base 作为脚手架的时候会遇到上面的问题，所以想是不是脚手架换成 npm ，会让厂外的使用者以及新接触到 fis 的新手可以少走一些弯路。希望这个 Issues 以后能给新手带来一点帮助。 ：）

**Comment by yanhaijing** [comment]
没有这个打算的原因主要是因为，我们不用，让我想想怎么做才好，一个fis-conf很难兼容这两种模式

**Comment by yanhaijing** [comment]
这个我也打算 换成 npm了

**Comment by yanhaijing** [comment]
已添加对npm的支持，添加了一个fis-conf-npm.js的配置文件
