### ISSUE TITLE
关于release之后的路径问题

### ISSUE THREAD

**Issue by Kelier** [yanhaijing/fis3-base#19]
/static/css/index.css是取不到的吧，应该是./static/css/index.css才能获取到资源吧

**Comment by yanhaijing** [comment]
fis里最好使用绝对路径

**Comment by Kelier** [comment]
可是demo用server跑起来之后，页面上这个替换之后的路径引用不到啊

**Comment by yanhaijing** [comment]
你可以把相信的信息再说一说吗？比如：

- 你怎么跑的？
- 浏览器看到的代码是？

**Comment by Kelier** [comment]
我搞清楚了，是自己有个图片替换路径搞错了，sorry
