### ISSUE TITLE
autoprefixer报错，无法release

### ISSUE THREAD

**Issue by simplees** [yanhaijing/fis3-base#5]
安装了fis-postprocessor-autoprefixer，release依旧会报错： [ERROR] unable to load plugin [fis3-postprocessor-autoprefixer] or [fis-postprocessor-autoprefixer] in [/index.html]。
fis3版本：v3.3.29
node版本：v4.2.2

**Comment by simplees** [comment]
还有sass编译使用了node-sass。

**Comment by simplees** [comment]
找到问题了，应该全局安装fis3-postprocessor-autoprefixer，而不是intro中的fis-postprocessor-autoprefixer。

**Comment by yanhaijing** [comment]
@simplees 我这里安装的是 fis-postprocessor-autoprefixer 哈？？？
