### ISSUE TITLE
写的es6的代码，依赖的babel-runtime怎么打包？

### ISSUE THREAD

**Issue by zhuzhuaicoding** [yanhaijing/fis3-base#6]
你好，我有个问题，我写的es6的代码，编译后了会require（babel-runtime），但是打包的时候没有一起打进去，怎么弄呢

**Comment by yanhaijing** [comment]
找到代码里的这一行：

```
fis.set('project.files', ['*.html', 'map.json', '/test/*']);
```

在中括号里添加上路径

**Comment by Avolons** [comment]
大神能加个扣扣吗

**Comment by yanhaijing** [comment]
@Avolons 就在这里讨论吧

**Comment by Avolons** [comment]
/c/Users/Administrator/AppData/Roaming/npm/fis3: line 14:  6848 Seg    mentation fault      node "$basedir/node_modules/.fis3_npminstall/fis3/3.4.17/fi    s3/bin/fis.js" "$@"
请问在执行的时候报这个错误是怎么回事

**Comment by yanhaijing** [comment]
这个不知道，在fis3的github issue查查
