### ISSUE TITLE
fis-parser-sass已经停止更新

### ISSUE THREAD

**Issue by canrz** [yanhaijing/fis3-base#7]
现在应该是fis-parser-node-sass。
css配置需改为node-sass，作者更新下吧。

**Comment by joneqing** [comment]
我配置成node-sass，使用fis3 release 报错.
Can't find 'compass-mixins/compass' in 'modules/html/header/header.scss'

**Comment by yanhaijing** [comment]
@joneqing 换成sass试试那？

**Comment by joneqing** [comment]
sass无法安装成功,console显示test failed,后面一堆报错
node -v 4.4.4

**Comment by yanhaijing** [comment]
你的node和系统是什么版本？想在windows安装fis-parser-sass 必须是node 0.10 和 0.12

**Comment by yanhaijing** [comment]
@joneqing 如果找不到其实可以写全路径，就能找到了

**Comment by joneqing** [comment]
ubuntu16.04 node v4.4.4

**Comment by yanhaijing** [comment]
@joneqing linux还没试过，windows和mac都用过了

**Comment by yanhaijing** [comment]
@joneqing 你写全路径吧，多敲一些字符而已

**Comment by yangluoGitHub** [comment]
@yanhaijing 怎么写全路径？不明白，作者可否指导一下

**Comment by yanhaijing** [comment]
项目的根目录
/modules/app/css/xxx

**Comment by wnghngxn** [comment]
没人维护这个项目和文档啊，导致一堆麻烦事情。有点不专业。

**Comment by yanhaijing** [comment]
哈哈。。。但是fis-parser-node-sass在windows真的是深坑无数啊，╮(╯▽╰)╭

**Comment by yanhaijing** [comment]
我实在不想折腾了

**Comment by wnghngxn** [comment]
虽然费了很多劲才搞定，但是仍然要感谢你们，因为我对fis是真爱。

**Comment by yanhaijing** [comment]
文档已更新：
mac系统推荐用 node-sass
windows 推荐用 sass
