### ISSUE TITLE
执行-wL命令时报错，其他fis3项目没有这个问题

### ISSUE THREAD

**Issue by Avolons** [yanhaijing/fis3-base#8]
按照步骤走的，把scss编译改成了node-sass插件，最终使用-wL监听文件更改时报错，错误显示为
/c/Users/Administrator/AppData/Roaming/npm/fis3: line 14:  3400 Segmentation fault      node "$basedir/node_modules/fis3/bin/fis.js" "$@"
我使用自己的fis3配置文件同样执行了一遍，并没有问题
node版本6.2.2
win7系统

**Comment by Avolons** [comment]
只要是执行release命令，都有这个错误

**Comment by Avolons** [comment]
问题解决了，因为我把组件里的compass删除了，导致了这个问题

**Comment by yanhaijing** [comment]
棒棒棒，node-sass你是什么平台

**Comment by yanhaijing** [comment]
我windows不能用这个

**Comment by Avolons** [comment]
fis-parser-node-sass
用了一个这样的插件，但是对compass的支持貌似有问题，我就把compass删掉了
